name: Push code to different Repo

on:
  push:
    branches:  master
  pull_request:
    branches:  master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        id: push_directory
        uses: dineshkumar6452/aem-learning@master
        env:
          SSH_DEPLOY_KEY: ${{ secrets.dinesh-deploy-key }}
        with:
          source-directory: output/
          destination-github-username: 'dineshkumar6452'
          destination-repository-name: 'dineshkumar6452/aem-learning@master'
          user-email: dineshkumar6452@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
